
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-25T21:10:41.703+05:30
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWorldWSService",
                      portName = "HelloWorldWSPort",
                      targetNamespace = "http://service.com/",
                      wsdlLocation = "file:/E:/Dropbox/Workspace/Webservices/HelloWorldClientApacheCXF/src/com/resources/HelloWorldService.wsdl",
                      endpointInterface = "com.service.HelloWorldWS")
                      
public class HelloWorldWSPortImpl implements HelloWorldWS {

    private static final Logger LOG = Logger.getLogger(HelloWorldWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.service.HelloWorldWS#sayHello()*
     */
    public java.lang.String sayHello() { 
        LOG.info("Executing operation sayHello");
        try {
            java.lang.String _return = "_return1649413501";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
