
package com.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-25T21:10:41.475+05:30
 * Generated source version: 3.1.7
 * 
 */
public final class HelloWorldWS_HelloWorldWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.com/", "HelloWorldWSService");

    private HelloWorldWS_HelloWorldWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldWSService ss = new HelloWorldWSService(wsdlURL, SERVICE_NAME);
        HelloWorldWS port = ss.getHelloWorldWSPort();  
        
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello__return = port.sayHello();
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
